plugin 'cocoapods-acknowledgements', :settings_bundle => true, :add_to_target => false

  target 'CetaceaSharedFramework-iOS' do
    use_frameworks!
    platform :ios, '10.0'
    project 'CetaceaSharedFramework/CetaceaSharedFramework.xcodeproj'
    workspace 'Cetacea'
    pod 'ReactiveObjC'
    pod 'DateTools'
  end

  target 'CetaceaSharedFramework-OSX' do
    use_frameworks!
    platform :osx, '10.12'
    project 'CetaceaSharedFramework/CetaceaSharedFramework.xcodeproj'
    workspace 'Cetacea'
    pod 'ReactiveObjC'
    pod 'DateTools'
  end

  target 'CetaceaSharedFramework-watchOS' do
    use_frameworks!
    platform :watchos, '3.0'
    project 'CetaceaSharedFramework/CetaceaSharedFramework.xcodeproj'
    workspace 'Cetacea'
    pod 'ReactiveObjC'
  end

  target 'Cetacea-iOS' do
    use_frameworks!
    platform :ios, '10.0'
    project 'Cetacea-iOS/Cetacea-iOS.xcodeproj'
    workspace 'Cetacea'
    pod 'DateTools'
    pod 'MMMarkdown'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'ReactiveObjC'
    pod 'DynamicColor', '~> 3.2.1'
    pod 'SDVersion'
    pod 'DKNightVersion'
    pod 'SyntaxKit', :git => 'https://github.com/SecondRenaissance/SyntaxKit.git'
  end

  target 'WatchKitApp' do
    platform :watchos, '3.0'
    project 'Cetacea-iOS/Cetacea-iOS.xcodeproj'
    workspace 'Cetacea'
    pod 'SDVersion'
  end

  target 'WatchKitApp Extension' do
    platform :watchos, '3.0'
    project 'Cetacea-iOS/Cetacea-iOS.xcodeproj'
    workspace 'Cetacea'
    pod 'SDVersion'
  end

  target 'Cetacea-Mac' do
    use_frameworks!
    platform :osx, '10.12'
    project 'Cetacea-Mac/Cetacea-Mac.xcodeproj'
    workspace 'Cetacea'
    pod 'DateTools'
    pod 'MMMarkdown'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'ReactiveObjC'
    pod 'SDVersion'
    pod 'DynamicColor', '~> 3.2.1'
    pod 'SyntaxKit', :git => 'https://github.com/SecondRenaissance/SyntaxKit.git'
  #pod 'Sparkle'
  end