workspace 'Cetacea'

target 'Cetacea-iOS' do
project 'Cetacea-iOS/Cetacea-iOS.xcodeproj'
workspace 'Cetacea'
use_frameworks!
end

target 'Cetacea-Mac' do
project 'Cetacea-Mac/Cetacea-Mac.xcodeproj'
workspace 'Cetacea'
use_frameworks!
pod 'MMMarkdown'
pod 'DateTools'
#pod 'Sparkle'
pod 'Fabric'
pod 'Crashlytics'
#pod 'SyntaxKit'
pod 'ReactiveObjC'
pod 'DynamicColor', '~> 3.2.1'
pod 'SyntaxKit', :git => 'https://github.com/SecondRenaissance/SyntaxKit.git'
end