language: objective-c
xcode_workspace: Cetacea-Mac/Cetacea.xcworkspace
xcode_scheme: CetaceaTravisCI
osx_image: xcode8.1

script:
  
  xcodebuild
  -workspace Cetacea-Mac/Cetacea.xcworkspace
  -scheme CetaceaTravisCI
  build

before_install:
  - brew update

notifications:
  slack:
    rooms:
      - fingameworks:Jq17wRjDEUVQiKlrVlNqzKr1#general
