language: objective-c
xcode_workspace: Cetacea-Mac/Cetacea.xcworkspace
xcode_scheme: CetaceaTravisCI
osx_image: xcode8.1

script:
  
  ./build/xcbuild
  -executor ninja
  -workspace Cetacea-Mac/Cetacea.xcworkspace
  -scheme CetaceaTravisCI
  build 
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO

before_install:
  - brew update
  - brew install cmake ninja
  - git clone https://github.com/facebook/xcbuild
  - cd xcbuild
  - git submodule update --init
  - make


notifications:
  slack:
    rooms:
      - fingameworks:Jq17wRjDEUVQiKlrVlNqzKr1#general
