# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Cetacea' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
#   use_frameworks!

  # Pods for Cetacea
pod 'MMMarkdown'
pod 'DateTools'
#pod 'Sparkle'
pod 'Fabric'
pod 'Crashlytics'
#pod 'SyntaxKit'
pod 'ReactiveObjC'

  target 'CetaceaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CetaceaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
